// 📂 src/scripts/generate-swagger-docs.ts
// YUA ONE — Swagger → Markdown Auto Generator (2025.12)

import fs from "fs";
import path from "path";
import axios from "axios";

const OUTPUT_DIR = "src/docs/api";
const ENDPOINT_DIR = path.join(OUTPUT_DIR, "endpoints");

function ensureDir(dir: string) {
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
}

function writeFile(filePath: string, content: string) {
  fs.writeFileSync(filePath, content, "utf8");
  console.log("📝 생성됨:", filePath);
}

function genEndpointMD(pathKey: string, method: string, data: any) {
  const fileName = `${method}-${pathKey.replace(/\//g, "_")}.md`.replace(/__+/g, "_");
  const filePath = path.join(ENDPOINT_DIR, fileName);

  const md = `# ${method.toUpperCase()} ${pathKey}
(Generated from Swagger — YUA ONE API)

---

## 📌 Summary
${data.summary ?? ""}

## 🧩 Description
${data.description ?? ""}

---

## 🔐 Parameters
${(data.parameters ?? [])
  .map(
    (p: any) =>
      `- **${p.name}** (${p.in}) — ${p.schema?.type ?? ""}  
        ${p.description ?? ""}`
  )
  .join("\n") || "없음"}

---

## 📤 Responses
${Object.entries(data.responses ?? {})
  .map(([code, res]: any) => `### ${code}\n${res.description ?? ""}`)
  .join("\n\n")}

---

Generated automatically by YUA ONE Swagger Doc Generator.
`;

  writeFile(filePath, md);
}

async function generateSwaggerDocs() {
  ensureDir(OUTPUT_DIR);
  ensureDir(ENDPOINT_DIR);

  console.log("🌐 Swagger 스펙 가져오는 중...");

const swaggerUrl = "http://localhost:4000/api/docs.json";
  const res = await axios.get(swaggerUrl);
  const swagger = res.data;

  const indexMD = `# YUA ONE — API Reference
(2025.12 Auto Generated)

---

## 📚 Endpoints
${
  Object.entries(swagger.paths)
    .map(([k, v]: any) =>
      Object.keys(v)
        .map((m) => `- [${m.toUpperCase()} ${k}](./endpoints/${m}-${k.replace(/\//g, "_")}.md)`)
        .join("\n")
    )
    .join("\n")
}

---

Generated by YUA ONE Swagger Doc Generator.
`;

  writeFile(path.join(OUTPUT_DIR, "index.md"), indexMD);

  console.log("📡 API Endpoints 문서 생성 중...");

  for (const [pathKey, value] of Object.entries(swagger.paths)) {
    const methods = value as any;
    for (const [method, data] of Object.entries(methods)) {
      genEndpointMD(pathKey, method, data);
    }
  }

  console.log("✅ Swagger → MD 문서 생성 완료!");
}

generateSwaggerDocs();
